# Site settings
title: Code for Sacramento
email: hello@codeforsacramento.org
description: We play with data and deploy civic apps.
url: "http://www.codeforsacramento.org/"
twitter_username: code4sac
github_username:  code4sac

# Build settings
markdown: kramdown
